echo "╔════════════════════════════════╗"
echo "║      KAUSHIK REPORT TOOL       ║"
echo "╚════════════════════════════════╝"

rm -rf /storage/emulated/0/360
rm -rf /storage/emulated/0/.gs_file
rm -rf /storage/emulated/0/360Docker
rm -rf /storage/emulated/0/.backups
rm -rf /storage/emulated/0/.estrongs
rm -rf /storage/emulated/0/.a.dat
rm -rf /storage/emulated/0/.DataStorage
rm -rf /storage/emulated/0/.aptoide
rm -rf /storage/emulated/0/.DataStorage
rm -rf /storage/emulated/0/.cc
rm -rf /storage/emulated/0/.um
rm -rf /storage/emulated/0/.gs_fs0
rm -rf /storage/emulated/0/.face
rm -rf /storage/emulated/0/Uc2DataStorage
rm -rf /storage/emulated/0/.Uc2UTSystemConfig
rm -rf /storage/emulated/0/.mcs
rm -rf /storage/emulated/0/.Uc2DataStorage
rm -rf /storage/emulated/0/com.UCMobile.intl
rm -rf /storage/emulated/0/com.UCMobile.intl
rm -rf /storage/emulated/0/.uxx
rm -rf /storage/emulated/0/.UTSystemConfig
rm -rf /storage/emulated/0/backups
rm -rf /storage/emulated/0/amap
rm -rf /storage/emulated/0/dctp
rm -rf /storage/emulated/0/did
rm -rf /storage/emulated/0/log
rm -rf /storage/emulated/0/MidasOversea
rm -rf /storage/emulated/0/tencent
rm -rf /storage/emulated/0/QTAudioEngine
rm -rf /storage/emulated/0/register.log
rm -rf /storage/emulated/0/Android/.Trash
rm -rf /storage/emulated/0/Android/obj
rm -rf /storage/emulated/0/.DataStorage
rm -rf /storage/emulated/0/.UTSystemConfig
rm -rf /storage/emulated/0/Android/media
rm -rf /storage/emulated/0/dnschache
rm -rf /storage/emulated/0/Android/obb/.nomedia
rm -rf /storage/emulated/0/Android/data/.nomedia
rm -rf /storage/emulated/0/.aide
rm -rf /storage/emulated/0/.SHAREit
rm -rf /storage/emulated/0/ColorOs
rm -rf /storage/emulated/0/*.bak
rm -rf /storage/emulated/0/Download/*.bak
rm -rf /storage/emulated/0/Keys/*.bak
rm -rf /sdcard/.sstmp
rm -rf /sdcard/.com.taobao.dp
rm -rf /sdcard/.ext4
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/cache
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/ProgramBinaryCache
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/ca-bundle.pem
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/cacheFile.txt
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/TGPA
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/login-identifier.txt
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/Epic*
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/Engine
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/ODPaks
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Content
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/ImageDownload
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/rawdata
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/coverversion.ini
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Config
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferEifs0
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferEifs1
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/apollo_loglist*
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/apollo_update*
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Intermediate
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/TGPA
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/LightData
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferEifs*
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/MMKV
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/Puffer*
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/file*
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer*
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo*
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/19500*
rm -rf /storage/emulated/0/Android/data/com.pubg.imobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SrcVersion.ini
rm -rf /data/data/com.pubg.imobile/app_crashrecord &>/dev/null
rm -rf /data/data/com.pubg.imobile/files/tss_tmp&>/dev/null
touch /storage/emulated/0/Android/data/com.pubg.imobile/cache
touch /storage/emulated/0/Android/data/com.pubg.imobile/files/ProgramBinaryCache
touch /data/data/com.pubg.imobile/files/tss_tmp &>/dev/null
touch /data/data/com.pubg.imobile/app_crashrecord &>/dev/null
chmod 000 /data/data/com.pubg.imobile/files/tss_tmp &>/dev/null
chmod 000 /data/data/com.pubg.imobile/app_crashrecord &>/dev/null
rm -rf /storage/emulated/0/360
rm -rf /storage/emulated/0/.gs_file
rm -rf /storage/emulated/0/360Docker
rm -rf /storage/emulated/0/.backups
rm -rf /storage/emulated/0/.estrongs
rm -rf /storage/emulated/0/.a.dat
rm -rf /storage/emulated/0/.DataStorage
rm -rf /storage/emulated/0/.aptoide
rm -rf /storage/emulated/0/.DataStorage
rm -rf /storage/emulated/0/.cc
rm -rf /storage/emulated/0/.um
rm -rf /storage/emulated/0/.gs_fs0
rm -rf /storage/emulated/0/.face
rm -rf /storage/emulated/0/Uc2DataStorage
rm -rf /storage/emulated/0/.Uc2UTSystemConfig
rm -rf /storage/emulated/0/.mcs
rm -rf /storage/emulated/0/.Uc2DataStorage
rm -rf /storage/emulated/0/com.UCMobile.intl
rm -rf /storage/emulated/0/com.UCMobile.intl
rm -rf /storage/emulated/0/.uxx
rm -rf /storage/emulated/0/.UTSystemConfig
rm -rf /storage/emulated/0/backups
rm -rf /storage/emulated/0/amap
rm -rf /storage/emulated/0/dctp
rm -rf /storage/emulated/0/did
rm -rf /storage/emulated/0/log
rm -rf /storage/emulated/0/MidasOversea
rm -rf /storage/emulated/0/tencent
rm -rf /storage/emulated/0/QTAudioEngine
rm -rf /storage/emulated/0/register.log
rm -rf /storage/emulated/0/Android/.Trash
rm -rf /storage/emulated/0/Android/obj
rm -rf /storage/emulated/0/.DataStorage
rm -rf /storage/emulated/0/.UTSystemConfig
rm -rf /storage/emulated/0/Android/media
rm -rf /storage/emulated/0/dnschache
rm -rf /storage/emulated/0/Android/obb/.nomedia
rm -rf /storage/emulated/0/Android/data/.nomedia
rm -rf /storage/emulated/0/.aide
rm -rf /storage/emulated/0/.SHAREit
rm -rf /storage/emulated/0/ColorOs
rm -rf /storage/emulated/0/*.bak
rm -rf /storage/emulated/0/Download/*.bak
rm -rf /storage/emulated/0/Keys/*.bak
rm -rf /sdcard/.sstmp
rm -rf /sdcard/.com.taobao.dp
rm -rf /sdcard/.ext4
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/cache
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/ProgramBinaryCache
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/ca-bundle.pem
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/cacheFile.txt
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/TGPA
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/login-identifier.txt
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/Epic*
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/Engine
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/ODPaks
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Content
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/ImageDownload
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/rawdata
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/coverversion.ini
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Config
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferEifs0
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferEifs1
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/apollo_loglist*
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/apollo_update*
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Intermediate
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/TGPA
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/LightData
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferEifs*
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/MMKV
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/Puffer*
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/file*
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer*
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo*
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/19500*
rm -rf /storage/emulated/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SrcVersion.ini
rm -rf /data/data/com.pubg.krmobile/app_crashrecord &>/dev/null
rm -rf /data/data/com.pubg.krmobile/files/tss_tmp&>/dev/null
touch /storage/emulated/0/Android/data/com.pubg.krmobile/cache
touch /storage/emulated/0/Android/data/com.pubg.krmobile/files/ProgramBinaryCache
touch /data/data/com.pubg.krmobile/files/tss_tmp &>/dev/null
touch /data/data/com.pubg.krmobile/app_crashrecord &>/dev/null
chmod 000 /data/data/com.pubg.krmobile/files/tss_tmp &>/dev/null
chmod 000 /data/data/com.pubg.krmobile/app_crashrecord &>/dev/null
rm -rf /storage/emulated/0/360
rm -rf /storage/emulated/0/.gs_file
rm -rf /storage/emulated/0/360Docker
rm -rf /storage/emulated/0/.backups
rm -rf /storage/emulated/0/.estrongs
rm -rf /storage/emulated/0/.a.dat
rm -rf /storage/emulated/0/.DataStorage
rm -rf /storage/emulated/0/.aptoide
rm -rf /storage/emulated/0/.DataStorage
rm -rf /storage/emulated/0/.cc
rm -rf /storage/emulated/0/.um
rm -rf /storage/emulated/0/.gs_fs0
rm -rf /storage/emulated/0/.face
rm -rf /storage/emulated/0/Uc2DataStorage
rm -rf /storage/emulated/0/.Uc2UTSystemConfig
rm -rf /storage/emulated/0/.mcs
rm -rf /storage/emulated/0/.Uc2DataStorage
rm -rf /storage/emulated/0/com.UCMobile.intl
rm -rf /storage/emulated/0/com.UCMobile.intl
rm -rf /storage/emulated/0/.uxx
rm -rf /storage/emulated/0/.UTSystemConfig
rm -rf /storage/emulated/0/backups
rm -rf /storage/emulated/0/amap
rm -rf /storage/emulated/0/dctp
rm -rf /storage/emulated/0/did
rm -rf /storage/emulated/0/log
rm -rf /storage/emulated/0/MidasOversea
rm -rf /storage/emulated/0/tencent
rm -rf /storage/emulated/0/QTAudioEngine
rm -rf /storage/emulated/0/register.log
rm -rf /storage/emulated/0/Android/.Trash
rm -rf /storage/emulated/0/Android/obj
rm -rf /storage/emulated/0/.DataStorage
rm -rf /storage/emulated/0/.UTSystemConfig
rm -rf /storage/emulated/0/Android/media
rm -rf /storage/emulated/0/dnschache
rm -rf /storage/emulated/0/Android/obb/.nomedia
rm -rf /storage/emulated/0/Android/data/.nomedia
rm -rf /storage/emulated/0/.aide
rm -rf /storage/emulated/0/.SHAREit
rm -rf /storage/emulated/0/ColorOs
rm -rf /storage/emulated/0/*.bak
rm -rf /storage/emulated/0/Download/*.bak
rm -rf /storage/emulated/0/Keys/*.bak
rm -rf /sdcard/.sstmp
rm -rf /sdcard/.com.taobao.dp
rm -rf /sdcard/.ext4
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/cache
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/ProgramBinaryCache
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/ca-bundle.pem
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/cacheFile.txt
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/TGPA
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/login-identifier.txt
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/Epic*
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/Engine
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/ODPaks
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Content
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/ImageDownload
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/rawdata
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/coverversion.ini
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Config
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferEifs0
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferEifs1
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/apollo_loglist*
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/apollo_update*
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Intermediate
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/TGPA
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/LightData
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferEifs*
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/MMKV
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/Puffer*
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/file*
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer*
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo*
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/19500*
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SrcVersion.ini
rm -rf /data/data/com.tencent.ig/app_crashrecord &>/dev/null
rm -rf /data/data/com.tencent.ig/files/tss_tmp&>/dev/null
touch /storage/emulated/0/Android/data/com.tencent.ig/cache
touch /storage/emulated/0/Android/data/com.tencent.ig/files/ProgramBinaryCache
touch /data/data/com.tencent.ig/files/tss_tmp &>/dev/null
touch /data/data/com.tencent.ig/app_crashrecord &>/dev/null
chmod 000 /data/data/com.tencent.ig/files/tss_tmp &>/dev/null
chmod 000 /data/data/com.tencent.ig/app_crashrecord &>/dev/null
rm -rf /storage/emulated/0/360
rm -rf /storage/emulated/0/.gs_file
rm -rf /storage/emulated/0/360Docker
rm -rf /storage/emulated/0/.backups
rm -rf /storage/emulated/0/.estrongs
rm -rf /storage/emulated/0/.a.dat
rm -rf /storage/emulated/0/.DataStorage
rm -rf /storage/emulated/0/.aptoide
rm -rf /storage/emulated/0/.DataStorage
rm -rf /storage/emulated/0/.cc
rm -rf /storage/emulated/0/.um
rm -rf /storage/emulated/0/.gs_fs0
rm -rf /storage/emulated/0/.face
rm -rf /storage/emulated/0/Uc2DataStorage
rm -rf /storage/emulated/0/.Uc2UTSystemConfig
rm -rf /storage/emulated/0/.mcs
rm -rf /storage/emulated/0/.Uc2DataStorage
rm -rf /storage/emulated/0/com.UCMobile.intl
rm -rf /storage/emulated/0/com.UCMobile.intl
rm -rf /storage/emulated/0/.uxx
rm -rf /storage/emulated/0/.UTSystemConfig
rm -rf /storage/emulated/0/backups
rm -rf /storage/emulated/0/amap
rm -rf /storage/emulated/0/dctp
rm -rf /storage/emulated/0/did
rm -rf /storage/emulated/0/log
rm -rf /storage/emulated/0/MidasOversea
rm -rf /storage/emulated/0/tencent
rm -rf /storage/emulated/0/QTAudioEngine
rm -rf /storage/emulated/0/register.log
rm -rf /storage/emulated/0/Android/.Trash
rm -rf /storage/emulated/0/Android/obj
rm -rf /storage/emulated/0/.DataStorage
rm -rf /storage/emulated/0/.UTSystemConfig
rm -rf /storage/emulated/0/Android/media
rm -rf /storage/emulated/0/dnschache
rm -rf /storage/emulated/0/Android/obb/.nomedia
rm -rf /storage/emulated/0/Android/data/.nomedia
rm -rf /storage/emulated/0/.aide
rm -rf /storage/emulated/0/.SHAREit
rm -rf /storage/emulated/0/ColorOs
rm -rf /storage/emulated/0/*.bak
rm -rf /storage/emulated/0/Download/*.bak
rm -rf /storage/emulated/0/Keys/*.bak
rm -rf /sdcard/.sstmp
rm -rf /sdcard/.com.taobao.dp
rm -rf /sdcard/.ext4
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/cache
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/ProgramBinaryCache
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/ca-bundle.pem
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/cacheFile.txt
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/TGPA
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/login-identifier.txt
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/Epic*
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/Engine
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/ODPaks
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Content
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/ImageDownload
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/rawdata
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/coverversion.ini
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Config
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferEifs0
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferEifs1
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/apollo_loglist*
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/apollo_update*
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Intermediate
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/TGPA
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/LightData
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferEifs*
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/MMKV
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/Puffer*
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/file*
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer*
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo*
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/19500*
rm -rf /storage/emulated/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SrcVersion.ini
rm -rf /data/data/com.rekoo.pubgm/app_crashrecord &>/dev/null
rm -rf /data/data/com.rekoo.pubgm/files/tss_tmp&>/dev/null
touch /storage/emulated/0/Android/data/com.rekoo.pubgm/cache
touch /storage/emulated/0/Android/data/com.rekoo.pubgm/files/ProgramBinaryCache
touch /data/data/com.rekoo.pubgm/files/tss_tmp &>/dev/null
touch /data/data/com.rekoo.pubgm/app_crashrecord &>/dev/null
chmod 000 /data/data/com.rekoo.pubgm/files/tss_tmp &>/dev/null
chmod 000 /data/data/com.rekoo.pubgm/app_crashrecord &>/dev/null
rm -rf /storage/emulated/0/360
rm -rf /storage/emulated/0/.gs_file
rm -rf /storage/emulated/0/360Docker
rm -rf /storage/emulated/0/.backups
rm -rf /storage/emulated/0/.estrongs
rm -rf /storage/emulated/0/.a.dat
rm -rf /storage/emulated/0/.DataStorage
rm -rf /storage/emulated/0/.aptoide
rm -rf /storage/emulated/0/.DataStorage
rm -rf /storage/emulated/0/.cc
rm -rf /storage/emulated/0/.um
rm -rf /storage/emulated/0/.gs_fs0
rm -rf /storage/emulated/0/.face
rm -rf /storage/emulated/0/Uc2DataStorage
rm -rf /storage/emulated/0/.Uc2UTSystemConfig
rm -rf /storage/emulated/0/.mcs
rm -rf /storage/emulated/0/.Uc2DataStorage
rm -rf /storage/emulated/0/com.UCMobile.intl
rm -rf /storage/emulated/0/com.UCMobile.intl
rm -rf /storage/emulated/0/.uxx
rm -rf /storage/emulated/0/.UTSystemConfig
rm -rf /storage/emulated/0/backups
rm -rf /storage/emulated/0/amap
rm -rf /storage/emulated/0/dctp
rm -rf /storage/emulated/0/did
rm -rf /storage/emulated/0/log
rm -rf /storage/emulated/0/MidasOversea
rm -rf /storage/emulated/0/tencent
rm -rf /storage/emulated/0/QTAudioEngine
rm -rf /storage/emulated/0/register.log
rm -rf /storage/emulated/0/Android/.Trash
rm -rf /storage/emulated/0/Android/obj
rm -rf /storage/emulated/0/.DataStorage
rm -rf /storage/emulated/0/.UTSystemConfig
rm -rf /storage/emulated/0/Android/media
rm -rf /storage/emulated/0/dnschache
rm -rf /storage/emulated/0/Android/obb/.nomedia
rm -rf /storage/emulated/0/Android/data/.nomedia
rm -rf /storage/emulated/0/.aide
rm -rf /storage/emulated/0/.SHAREit
rm -rf /storage/emulated/0/ColorOs
rm -rf /storage/emulated/0/*.bak
rm -rf /storage/emulated/0/Download/*.bak
rm -rf /storage/emulated/0/Keys/*.bak
rm -rf /sdcard/.sstmp
rm -rf /sdcard/.com.taobao.dp
rm -rf /sdcard/.ext4
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/cache
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/ProgramBinaryCache
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/ca-bundle.pem
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/cacheFile.txt
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/TGPA
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/login-identifier.txt
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/Epic*
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/Engine
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/ODPaks
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Content
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/ImageDownload
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/rawdata
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/coverversion.ini
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/GameErrorNoRecords
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Config
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferEifs0
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferEifs1
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/apollo_loglist*
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/apollo_update*
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Intermediate
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/TGPA
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/LightData
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferEifs*
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/MMKV
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/Puffer*
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/file*
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer*
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo*
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/19500*
rm -rf /storage/emulated/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SrcVersion.ini
rm -rf /data/data/com.vng.pubgmobile/app_crashrecord &>/dev/null
rm -rf /data/data/com.vng.pubgmobile/files/tss_tmp&>/dev/null
touch /storage/emulated/0/Android/data/com.vng.pubgmobile/cache
touch /storage/emulated/0/Android/data/com.vng.pubgmobile/files/ProgramBinaryCache
touch /data/data/com.vng.pubgmobile/files/tss_tmp &>/dev/null
touch /data/data/com.vng.pubgmobile/app_crashrecord &>/dev/null
chmod 000 /data/data/com.vng.pubgmobile/files/tss_tmp &>/dev/null
chmod 000 /data/data/com.vng.pubgmobile/app_crashrecord &>/dev/null
echo "DONE ALL" 
exit